### ISSUE TITLE
TypeError: L.a.createElement is not a function

### ISSUE THREAD

**Issue by Shiloha** [karan101292/react-video-js-player#14]
Hi, 

I was looking for ways to customize the video player and wanted to try this but I'm getting an error. 

Have you seen this error? If not, perhaps you need to add the react-dom package as suggested in [stackoverflow](https://stackoverflow.com/questions/38166125/reactjs-react-render-is-not-a-function-and-react-createelement-is-not-a-functio).
---------------------------------------------------------------------------------------
> Build error occurred
TypeError: L.a.createElement is not a function
    at [path_to_project]\node_modules\react-video-js-player\build\index.js:8:173271
    at Module.<anonymous> ([path_to_project]\node_modules\react-video-js-player\build\index.js:8:173561)
    at n ([path_to_project]\node_modules\react-video-js-player\build\index.js:1:124)
    at [path_to_project]\node_modules\react-video-js-player\build\index.js:1:923
    at Object.<anonymous> ([path_to_project]\node_modules\react-video-js-player\build\index.js:1:933)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  type: 'TypeError'
}
------------------------------------------------------------------------------------

**Comment by Mamtak** [comment]
I am also getting the same error. Any Update on This.

**Comment by Shiloha** [comment]
No, I just used https://www.npmjs.com/package/react-player instead.

**Comment by Usama176** [comment]
What is the solution of this error

**Comment by the-wdr** [comment]
Getting it too. Is possible a bug from Webpack.
